<?xml version="1.0" encoding="utf-8"?><Database Name="TIM_TROO" Class="TimNhaTroDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.ANH_CCCD" Member="ANH_CCCDs">
    <Type Name="ANH_CCCD">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCardPhoto" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IdCardPhoto2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="TAIKHOAN_ANH_CCCD" Member="TAIKHOAN" ThisKey="IdTaiKhoan" OtherKey="Id" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONHANG" Member="DONHANGs">
    <Type Name="DONHANG">
      <Column Name="IdDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Id_NguoiDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Phong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NGUOIDUNG_DONHANG" Member="NGUOIDUNG" ThisKey="Id_NguoiDung" OtherKey="Id" Type="NGUOIDUNG" IsForeignKey="true" />
      <Association Name="PHONGTRO_DONHANG" Member="PHONGTRO" ThisKey="Id_Phong" OtherKey="Id" Type="PHONGTRO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHUTRO" Member="CHUTROs">
    <Type Name="CHUTRO">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Facebook" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Id_TaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CHUTRO_PHONGTRO" Member="PHONGTROs" ThisKey="Id" OtherKey="Id_ChuTro" Type="PHONGTRO" />
      <Association Name="TAIKHOAN_CHUTRO" Member="TAIKHOAN" ThisKey="Id_TaiKhoan" OtherKey="Id" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOTRO" Member="HOTROs">
    <Type Name="HOTRO">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sdt" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MotaVande" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IMAGES" Member="IMAGEs">
    <Type Name="IMAGE">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_PhongTro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Url_Path" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Url_Path2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Url_Path3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Url_Path4" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Url_Path5" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="PHONGTRO_IMAGE" Member="PHONGTRO" ThisKey="Id_PhongTro" OtherKey="Id" Type="PHONGTRO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIDUNG" Member="NGUOIDUNGs">
    <Type Name="NGUOIDUNG">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Facebook" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Id_TaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NGUOIDUNG_DONHANG" Member="DONHANGs" ThisKey="Id" OtherKey="Id_NguoiDung" Type="DONHANG" />
      <Association Name="TAIKHOAN_NGUOIDUNG" Member="TAIKHOAN" ThisKey="Id_TaiKhoan" OtherKey="Id" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHUVUC" Member="KHUVUCs">
    <Type Name="KHUVUC">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Slug" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="KHUVUC_PHONGTRO" Member="PHONGTROs" ThisKey="Id" OtherKey="KhuVuc" Type="PHONGTRO" />
    </Type>
  </Table>
  <Table Name="dbo.PHONGTRO" Member="PHONGTROs">
    <Type Name="PHONGTRO">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_ChuTro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Slug" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AnhBia" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="GiaCa" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="HoaHong" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DienTich" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Map" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Video_link" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Ngay" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(155)" CanBeNull="true" />
      <Column Name="Nuoc" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Dien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Internet" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="GuiXe" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="KhuVuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoNguoiO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="PHONGTRO_DONHANG" Member="DONHANGs" ThisKey="Id" OtherKey="Id_Phong" Type="DONHANG" />
      <Association Name="PHONGTRO_IMAGE" Member="IMAGEs" ThisKey="Id" OtherKey="Id_PhongTro" Type="IMAGE" />
      <Association Name="CHUTRO_PHONGTRO" Member="CHUTRO" ThisKey="Id_ChuTro" OtherKey="Id" Type="CHUTRO" IsForeignKey="true" />
      <Association Name="KHUVUC_PHONGTRO" Member="KHUVUC1" ThisKey="KhuVuc" OtherKey="Id" Type="KHUVUC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhanQuyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Association Name="TAIKHOAN_ANH_CCCD" Member="ANH_CCCDs" ThisKey="Id" OtherKey="IdTaiKhoan" Type="ANH_CCCD" />
      <Association Name="TAIKHOAN_CHUTRO" Member="CHUTROs" ThisKey="Id" OtherKey="Id_TaiKhoan" Type="CHUTRO" />
      <Association Name="TAIKHOAN_NGUOIDUNG" Member="NGUOIDUNGs" ThisKey="Id" OtherKey="Id_TaiKhoan" Type="NGUOIDUNG" />
    </Type>
  </Table>
</Database>